Repository Roamer15/Alimana, pull requests merged in 2025-07, with the labels that each got.

#4 Update .coderabbit.yaml
  .coderabbit.yaml
Labels: architecture-improvement

#10 Feature/store manager
  package-lock.json
  package.json
  src/app.module.ts
  src/common/context/request-context/request-context.controller.spec.ts
  src/common/context/request-context/request-context.controller.ts
  src/common/context/request-context/request-context.module.ts
  src/common/context/request-context/request-context.service.spec.ts
  src/common/context/request-context/request-context.service.ts
  src/common/errors/error-codes.enum.ts
  src/common/errors/error-messages.ts
  src/common/middleware/payload-context.middleware.ts
  src/database/migrations/1752632912376-AddEmailProfilUrlToStore.ts
  src/database/migrations/1752633372633-AddUserStoreRelation.ts
  src/database/migrations/1752635941611-AddCategoryToPermissions.ts
  src/database/migrations/1752636706763-SeedDefaultPermissions.ts
  src/entities/User.entity.ts
  src/entities/permission.entity.ts
  src/entities/store.entity.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/guards/jwt-auth.guard.ts
  src/modules/auth/guards/store-jwt.guard.ts
  src/modules/auth/strategies/store-jwt.strategy.ts
  src/modules/store/constants/exp.ts
  src/modules/store/constants/store-default-settings.ts
  src/modules/store/dto/create-store.dto.ts
  src/modules/store/store.controller.spec.ts
  src/modules/store/store.controller.ts
  src/modules/store/store.module.ts
  src/modules/store/store.service.spec.ts
  src/modules/store/store.service.ts
Labels: architecture-improvement, testing-enhancement, api-design, security-review

#12 Feature/store manager
  src/app.module.ts
  src/common/errors/error-codes.enum.ts
  src/common/errors/error-messages.ts
  src/database/migrations/1752747364027-CleanUpStoreUserColumns.ts
  src/database/migrations/1752747744153-FixRolePermissionsJoinTable.ts
  src/database/migrations/1752748634533-CleanUpPPayementSaleItemSaleSaleReceiptsColumns.ts
  src/entities/payment.entity.ts
  src/entities/role.entity.ts
  src/entities/sale-item.entity.ts
  src/entities/sale-receipt.entity.ts
  src/entities/sale.entity.ts
  src/entities/store-user.entity.ts
  src/entities/store.entity.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/decorators/permissions.decorator.ts
  src/modules/auth/guards/permissions.guard.ts
  src/modules/auth/guards/store-jwt.guard.ts
  src/modules/auth/strategies/store-jwt.strategy.ts
  src/modules/store-setting/store-setting.controller.spec.ts
  src/modules/store-setting/store-setting.controller.ts
  src/modules/store-setting/store-setting.module.ts
  src/modules/store-setting/store-setting.service.spec.ts
  src/modules/store-setting/store-setting.service.ts
  src/modules/store/constants/exp.ts
  src/modules/store/constants/permission-enum.ts
  src/modules/store/store.controller.ts
  src/modules/store/store.service.ts
  src/shared/guards/ee.ts
Labels: architecture-improvement, testing-enhancement, api-design, security-review

#14 Feature/create sale session
  src/app.module.ts
  src/database/migrations/1752636706763-SeedDefaultPermissions.ts
  src/database/migrations/1752890741461-UpdateCashRegisterSessionAddcasgMovement.ts
  src/entities/cash-movement.entity.ts
  src/entities/cash-register-session.entity.ts
  src/entities/store-user.entity.ts
  src/modules/cash-movement/cash-movement.controller.spec.ts
  src/modules/cash-movement/cash-movement.controller.ts
  src/modules/cash-movement/cash-movement.module.ts
  src/modules/cash-movement/cash-movement.service.spec.ts
  src/modules/cash-movement/cash-movement.service.ts
  src/modules/cash-movement/dto/create-cash-movement.dto.ts
  src/modules/cash-register-sessions/cash-register-sessions.controller.spec.ts
  src/modules/cash-register-sessions/cash-register-sessions.controller.ts
  src/modules/cash-register-sessions/cash-register-sessions.module.ts
  src/modules/cash-register-sessions/cash-register-sessions.service.spec.ts
  src/modules/cash-register-sessions/cash-register-sessions.service.ts
  src/modules/cash-register-sessions/dto/close-session.dto.ts
  src/modules/cash-register-sessions/dto/open-session.dto.ts
  src/modules/store-setting/store-setting.controller.ts
  src/modules/store/constants/permission-enum.ts
Labels: architecture-improvement, testing-enhancement, api-design, security-review, database-optimization, performance-optimization

#13 Feature/cashier session
  package-lock.json
  package.json
  src/app.module.ts
  src/common/errors/error-codes.enum.ts
  src/common/errors/error-messages.ts
  src/modules/cash-register/cash-register.controller.spec.ts
  src/modules/cash-register/cash-register.controller.ts
  src/modules/cash-register/cash-register.module.ts
  src/modules/cash-register/cash-register.service.spec.ts
  src/modules/cash-register/cash-register.service.ts
  src/modules/cash-register/dto/create-cash-register.dto.ts
  src/modules/cash-register/dto/update-cash-register.dto.ts
Labels: architecture-improvement, testing-enhancement, api-design, security-review, database-optimization

#16 Feature/products
  src/app.module.ts
  src/common/errors/error-codes.enum.ts
  src/common/errors/error-messages.ts
  src/modules/category/category.controller.spec.ts
  src/modules/category/category.controller.ts
  src/modules/category/category.module.ts
  src/modules/category/category.service.spec.ts
  src/modules/category/category.service.ts
  src/modules/category/dto/create-category.dto.ts
  src/modules/category/dto/update-category.dto.ts
  src/modules/products/dto/create-product.dto.ts
  src/modules/products/dto/update-product.dto.ts
  src/modules/products/products.controller.spec.ts
  src/modules/products/products.controller.ts
  src/modules/products/products.module.ts
  src/modules/products/products.service.spec.ts
  src/modules/products/products.service.ts
Labels: testing-enhancement, api-design, security-review, database-optimization

#17 feat(invitation): complete implementation of the invitation process
  package-lock.json
  package.json
  src/app.module.ts
  src/common/email/email.service.ts
  src/config/config.service.ts
  src/entities/store-user.entity.ts
  src/modules/invitation/dto/invitation.dto.ts
  src/modules/invitation/invitation.controller.spec.ts
  src/modules/invitation/invitation.controller.ts
  src/modules/invitation/invitation.module.ts
  src/modules/invitation/invitation.service.spec.ts
  src/modules/invitation/invitation.service.ts
  src/modules/sales/sales.controller.ts
Labels: testing-enhancement, api-design, security-review

#19 change datasource
  src/database/data-source.ts
Labels: architecture-improvement, database-optimization

#20 command migration
  src/database/migrations/1752632912376-AddEmailProfilUrlToStore.ts
Labels: database-optimization
